### ISSUE TITLE
Unexpected Behaviour on Codeforces unavailable page 

### ISSUE THREAD

**Issue by arpan-dasgupta** [GaurangTandon/codeforces-darktheme#21] opened 2019-02-19 11:53 UTC
![screenshot from 2019-02-08 20-50-10](https://user-images.githubusercontent.com/43383607/53013110-f00be580-346a-11e9-998f-012652d9c986.png)

**Comment by GaurangTandon** [comment] 2019-02-19 15:48
If I understand this correctly, the only fix you desire from my side in this case is to make the text color white, isn't it?

I certainly can't fix the server issues :P

**Comment by arpan-dasgupta** [comment] 2019-02-19 18:57
Yeah the text color could be white and the background completely black as it is on the homepage.

**Comment by GaurangTandon** [comment] 2019-02-20 02:45
Alright. Can you please also show the inspect element result next time this happens? Because as of now I cannot reproduce this webpage state. I'll keep an eye out too. Thanks!

**Comment by user202729** [comment] 2020-04-10 12:07
It's possible to get Codeforces's error page by allowing browser's caching (I think this is on by default), disconnect the Internet then open any Codeforces page.

This page has black text too. (HTML source below)

```
<!DOCTYPE html>
<html lang="en">
<head>
<meta http-equiv="content-type" content="text/html; charset=UTF-8">
<meta charset="UTF-8">
<title>Codeforces</title>
<style>
body {
width: 760px;
margin: 2em auto;
font-size: 22px;
}
 
p {
margin-top: 4em;
}
</style>
</head>
<body>
<img src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAASwAAABBCAYAAABrYJlFAAAWC0lEQVR4Xu2dC5AcVb3/ocQqtVJXQMSEfT/yQEJBKZhIwQURrygoXC9XkcsV/BslCBLASLCKEGRJiOaBGDGBBCNyFXlogBB5bDYhu0s2ySbZ3ewrD/IgIYn80RvCIzszO7vf259Knaqu3p4+M9MTdwnnW/Wr6T59+nfOnNT55Pc7fab3GL1P5OTk5HT0A8vJyckBy8nJyckBy8nJyckBy8nJyQHLycnJyQHLycnJyQHLycnJAcvJycnJAcvJycnJAcvJyckBq19SSlKPpAOS3pb0lu+T8pQGW05OTg5Y/f39O8Y+uk2VCzep6DdtKn6oU6WLulX0YIeK5rer9KEu/WjFDg06tJycnBywLntiu0oWdERaxfwO/X7z/3bqAyEnJ6dDhw5p37592rVrl95++20Cm6EBrDMf3qzi+e2RVvLAJs1bv/+gjno5OTldc801GjZsmObMmaPf/e53Gjt2rEaMGKGdO3cOPrDGPtRtBVbpbzo1o/G1hI5qOTk5XXXVVTrmmGN08OBBGaXTaZ144ok67rjjBh9Ypy/q8IDUHm0Ltmh6w66jHFhOTk4nn3wywFJQZ599NuXq6uoaXGCduqhTJfPaIq3ogS5Nr9+to1tOTk4f/ehHQ4E1btw4yrV79+5BXsNa0K3iX7VGWtGvOjSzcU9aR7WcnJw+/OEPhwKLNawPfehDBUsJWcXfknyrY13qra3PpN77+8OJt9rXJd5a/0biQGddb/KdxX196RWhwPp1q0rvj7aieZv088bdCX1g5OTkgPWHP/xBNTU1WrhwoYqKinhyWBhg9aV7V/Tsvl/Jbderr3uy+jbfpfTW29S39VZp81T1d01WYtssATIFNGZRiwVYRFmbNKN+V1pDRAcOHNCSJUs0bdo0XXbZZTr//PONcU4516mn/OTk5IDV1NSk3/72t/rjH/+oj33sY5o9e3ZhgJXc+Wv1b54idU9R75YpSm/5ibT5p0p7ZZSnN9/ulf1YfTsGNnj6/DaV/qol0kbPbdPU+j0abK1cuRIgMaBZG49ouS9/OTm5lPCKK66gXFOmTIkPrJ4dc5Xu8oDU+WMlN9+idPck9XXfplT3LURc6vWO+zbfrPT2WaHAKvllS6QN/+V6zWzamx7EiMoCKrtxP/tIcpeTkwNWMpmknEV5tjnEA1Zixy+U7rwJU6L7JvV23aC+rluU7L7R+5yk3s5bvbIbldo2cyCwftOqUg9KUUaUNWdV1tsa+gsNqzPOOCMWrIIRl4MXkhYvXqxCqnH9Lu3//2+rsHJq7drHuA4qsBDlWFtbW8wIa/tMD1YenDpuUKLrhx6gJgIvpTp/qH6vPNX5I8qU3HKPghr7gAekuRsjrey+Ft1d9+oAEPX19W159Yaf6uWzztOmsy5Uy/gvqO5z56jl8xeq4/Tz1fyt7+jtfa8/HON3iJGwYs3qvvvuI+XzG2VAKfI+m1paWlgLo66/D2adjDZs0KMv+MjFzPfJBjbUz9sYA8wI0Dzylw152wP/06TLJv6eyaVM2rbr79TVrTOWYbromocxjjX1l7V66oV2C/Di9fOF+q16592EshVt0Sf6Rh/5fvT3qlv/xLl+/tAqm09gU8BxtffRjOkP7ljCOT4Y94ICa/v27TGBte1eD1Y/VN+m65XsuF6pjuuAl1Lecbr9evVy3PF9D1h3DwTWPKC0IdKGe9CaUz9gW0N/62f/TfXDq7S6bLSaiqu1uqhCjaXlaiivUkNptRpLRnvnn1Y6lVqhPDRp0qQw4AAQYJBVdAYE/D4+/vGPR4IGv2VlZblEbJn8UQ4UsvUV7Ce+Mz044KFC9v7s4GbSGYjEsTBgUZaLb+pmAhf9BCBx+ghoosBIG9TJ1h9AoT73hQHlSIwrbQGzbH0AWeDFffQpb2CdcMIJBVh03zZdfe3XYUp2Xqfe9gmH4dX+A8qUxjq+p+TWuxTUafe3qGzO+kgbdV+7ZtbvTgejq7rqU1VfXaXlVSP1clm11o46TcsrK1VbUaW11aepoXiUGstP1d+aNryo3AQEMsEqZBJboyUDISIYCyDzgksmgPqBma9v+m+JPmMDy6R0hQYWkyQfP0CA6CVT1BK3n/gHMGFRINfy9QkU6J/fN2WFBhYRVBx/QCsnYNXV1VGuBQsWxAdWwgNRX/v31dc2QcmO/+cB6rveOeDyjjdhEyhTavO0cGDNao60U2Y3a8aKXYGtFOnWl8orVe+Bqr6k2oMTn55VjNbyslF6sbjKg9hoNZSM1t9eWrWrENEVYABWecikQVE/+Iya2Maioi/AUjhg2aNC+hMXWIUGAT5ssPKnLBgpVqZ6QOtIAAujf8FoCOjY+mwsClz4KjSwovzRpkkBMSK+TH3kmjXCGj9+vOrr6/kpjhYtWkS5br/9dqH4Twm33qneTdcq3XatEu3XKtX2X+pt+66Sm/6bMo6969/xgHWnAuo/3QNW6S+aLbZO01e8NgBYjR6YVpSO0cqKSq2sGqXl5dWYGirHqLF8tFaUVRFx6c26hl2FWLsCOjGUa3oFNLknLG0M6x8wo74NWFFRJW1mSj0twMppfGgrK2DlIFI1fERBhTqAIQxCAMEeCRnf9lTUGj0CHZ8yQsikUiECqMH7WFOyRpk5CMD4gRUEfKZ0FFFOH/33ZJUS9vT0kDXowQcf5FP/+Mc/hAoDrC3T1OtBqq/120q1e2BquRpQecD6tnpbrwFgSrZerVT3TxXU2LnNKv/5OqvNrAtGWH2ttR6castHqa5iZKTtW76yU7kpDCBH6sleWNTEonY+Ty9JOe3AsqewRFW2728Hll2FBJZ18jOxLApbO2KtJh6wwic6fYwCGrDMesEaSBkgIxuw4ijoCyhZRB0iRMY330X3AgJr81QlW76ldOu3lGi72jv+NtBSsu3Kw5+tVx3+7L5NQZ12X7PKZq6NsozAeqmsCmCJzygDWIVYvzoCAg5he7ay7WcQLEAsLrAQwLTAMCdgAVh8xgeW/XE7ZRHRjHViAYogOOICC/BE9Sl0IR+I5SCASP9jAsu+PQSQBsFrB7aAbyTc2F917LHHYkceWL0bPWBtvAI4HT5uuUqJ1m96xx68PJABtDBgfXruOg9KNlsbCSwirQjLFViEoJb1lliyAgWIRci29lUIYAGYsBQ1Clic27Yx5AqsfB63M+Ei1qKsCnv6BXCi+knkENVXYBJ2T0YIEI0USPShEOMaAdfw9SzMjAuwsqmzs5M5oDPPPPPIAivRfbt6W65Q34Z/98D0TaU2/qfSGzxAtX5Dveu/yTXKlOycHA6sGWsjrfTeNZqxfOcAYL1QVqkXy0da7fXldRZgWScr9k8DVg4i6gneD3AL4Z9oLQikOIvu2QEr/jYGIJF72mKPoCKux35SFgaUQgIr/rjGf5oLtCP9Pv300zrnnHP0+OOPH2Fgdf1EqQ2Xq6/56x6Y/kPJ9Zcp3fwNJTd+nU/vmle+/htKdN6ioE6d4wFp+ppIK5nRpOm1O4Lh4waA9deyar1gMYA1JNew4gMLOB0pYAGYowZYaIgAiwjEpHtDHVj2KNRuMaLdIwQsQNTbfIkHp68ehtO6S5Ve9zUlN3zVK/+aetcf/kx1TAoFVsk9TZFWPH11KLCWlVVoWXk10IowgLXCAizLZI2/qEzUBvCyARZ140RYpJSFABbrY7kAi4cHlIUZvvIBFmlFmJEy5QKsXHZbA5MjASxSqUw70y0L/bGBFXdcLU8ocwb24AIr2X4TsPIg9WUl11+i3nVf8c4vUWr9lzj27MsexL6qZMeNA37rN2b2GhXXrI626U3hwCqt0nNlnpVURlk+wAIElk2UOUdSpFjZLG5TFgesNiDm++ABX7ZFd9uWiVyBZXsyBoiy8UPdXB7jh6VvtgjMFoFQlvUTRM5zlOlj7IjTrDnlIOoDOWCfzV4s6g9ihNV+A1BS35qLlGr+ipJrPFCtuVjJ5guVWnuxByuvfO1XqDcAWKNnNVmBVXTPatW8tDMUWM+WA61oA1h5REQAKmyne66pIfusjC8AYgOD2U+VTzrIE0YbsPJdzOd7vB+2NRDB2PdT2Z/mBeFhA1bYY3xbPT/g4qaFhU2R7VGobzytkVjYdxs0YPWn2iYq3fRFz4iwzldi3eeBlg6tP9c7/qJ6PJD1A7O26xRU1ezVGl7TpJN/9opGeKnfiLsbMSClU2q8sru96/ds0IwXtw4A1jNF1frLmDItLR+j50pH66/lp2pJcbWeLxmtlSVe2YgKPVtRrddeqt0uFD/KMpFWNlEQ0VjYxKfcFiWZ3/HluleKfsUFFj7su/zjAwtY47MwwLJHSQAkBFrWn8UAjlyBZfzZwRncimGHVtTvBc3WhkIDC5AHt37kAh3qDx1gJTq/q55XvJSv6TNKrT5X/SsvkRq/pPSaC5RY/QX1rfUgtma8DrV+T0GNmtGgT9U06uS7G3TKjCYPTo365M9WcU45ENMnahp0d+2rwTc1dC4trdayopF6prJaT4wo1bMlVVpaOVp/Kq/U41WVlGtZcYX2sq0hP0W9dYFIiDTH/8YGgEFZ1O/suGaDj/GPPya2vy7+oxa1bcCin2EGoP0QssGIumEvK8zWzI/ICwms4KQKA4Z5K0PwLQ5cC4UcyglY9vWjXBaygRBRCn32Q4Mox77RNbwP9DdbY7zoc1jERN9oj3qZQGfZYzYYEVbrBPWsPs+D0oV6d8OFOrR2vBJN/6oeD1SHms7DlGoep/TGawbcWz13HVGUTpq6Sp+4s16fvKuRaEuf8so+xfG0Bs5114sDgcVTwudGjCaS0rLKMXqmfKSeLR6pp0tG6kkPZk+VjdRzJaO0Y1ntG4P08r5glAJAzKthbFGN3ew/yjbAius7av0sjhUeWPF/SBzcaR4HWAhAZbumZtLIuEa/4zwljIIsfbTtwYqswzU0iCnhdUo0fhYDWnpv9XgPUhx/TunGz3sw+5LeazhD6rhtwL2fnltPJKWTAFPNakwnTqvX8VNf1gl3rjoMrqlNWti440DwbQ1LTinXXyor9ERpmZ4qKdPTRWVa5pUReT1ZXqUnyqq98irt3dTxRAG2HwCcOKACKLY1qXzaABzGd6GBBawz+SYCLCSwiCLCFrvjQivqx81Rk4q283mKmG26h5+4r6+x7DgvOLAAYRw/Ji0fXGD17Fvb+W7LBUq+fLbSL5+rXg9OqfpxHsA+o/SqcR7AztTBtV9U6t39i4P3Ptb898TxdyzXCVPrdNLP6j1IrdS/3LlCn/RSwk/ctcorX6ERv/ir0um+ZgXUPGmK/lw0yoPWSC0pr/YMQFXo2bKRh1NF79ryM8bxF332Kr7Mk65sJyr1AqCyirrZwpHIh8jM9m6tfAALqAxM7CCMDyzgAFii0qc46SGTNug/Mv0KUVQ/KeOaPdUL3+0e5x1e5kffmfzQt0IBywAYMzv4c3ofltGgACuoxN6n1LNnsXpef1rv7fuz3t3/vFe2VMndT3E5EzT6G3cfqntkzd435tZu63+g/rXEg6/sOXj/yh3JeS/vTDzS/Lc3vGiqmXoaqNTrr6xZ1TF/oToXLFLXwsXqfmixXl34iNrun6+uZc8dhAHcewR+A5jxrZuUcz2mzLpSmH/gmQ1g8ZGLAcxsv7/FV05rWEAl4xpKAUWEQDoW+jZQrkXI1k+uRT3yz2S2BXWzVSBo5kmd7f6wNmOsYeXUx+DWkyEFLCenGE8Jh7Cc4kLngwcsJycnJwcsJycnBywnJ9a5Hn30UTU0NKi3t1dHs8rLy9Xc3Kyg+OvFY8aMURx1d3dnXAd85513lEk333yzbrzxRgcsm5ycJkyYoJNOOom/2MuEPeonjnniGRRlwCyOeJf5BRdcgOkjH/kIADTnam9vVyZde+21mAOWk1M2P5zetm2bv8wBK77wFdzKEgNYDlhOTvyvD7BCU6T9+/fr4osvVm1trc466yyNHTtWNTU1A34sftFFFzE5+cSPfxLqscce08SJE1VdXa3LL78cnzKaNWsWPolCtHDhQn96qksvvRSf/EUW2pDR/PnzNW/ePF199dVcp/9C9957r/FFeuVPa4EGb8bkOsc2YFGHutxj+kW6TJ+C0RTjkS2wSAmJZhkL4zsjsBgDojJ88G9AqulPXc8991yuUQejf0L4BbyMA/5ok4iZc9ql/TfffNP/78syAP6ow1jTtjlnXP+pwOo/6qzgcgI0pITsI+MvoPgjLdIaJgeTBHBRDwghzo8//niAQl1gxrmZEEwkzvELhICemZRMEnyxVYL6ev75502b+AAUHOvJJ5+kD7RvNsFyH5OQe7gX//gmSqQesKGegR/348dMzEhgHXfccYCJ+4Aj5/jUnj17/D+GB4j0A5hmDSyADUToM/0ZNmwYbQ4AFmOCbyBEXYADbGiTfx8z5vQJ4PAfAmBC9BHYch3fgI7xYWwwxgnQ+v99gRzQuuOOOzinLS1duhQf5j+zoQMsBywnJoIBwfDhwwGRP100AEKAgrUuISZL8H9gYEEEZIA1efJkf3TEdQMsJmxwXYdJw8QesMaGGWARdfnFBANeRgCMSYhoHwD5opwoYPH9AYMf5vQpeGzgTd2sgGWAB3D8ACMaDAKL8QNE/j4DEsABdICoaReoMs5GtBEFUUBOO/5/XxP10jfOgZWRiUqHGrAcsJyYTKRvRDjmrathLxk0E4SUIbhGwzXqBI8Rdf1rRERkTETAZyIXUj2gEGwTWAQnnBETGNDg2xiQ8vvLaw0rCBIinuLiYuMXeGe7hgWgaZcyvzEGwXaImIB5sC5jBFSAKiAGmoDZ+EDB14MDNiBrUkKisyCwosYGGA5ZYDlgOZE2mDQgFFikEyYCIr0iGvCJ6IcIxwosf/QAJIlWEBAABuHQCAeWiQpDRF2imHyBxXelTQN0QEJbfJIqZgssUjPa9UdkUd8R4GZaczTrdNRnrPGZCVhEa0CNKMr4fv8CywHLiVQKMyLFAx5MTgMsUkDAQupAhAF4DDxIGUzKCASImLjPBiwmHj4RE5/7zCI+7TPBEZ9EBfQxE7AAHGAxMDB9R6yFATT6znXgFQUsrvEwgLq0DZiIjvzpqYlWULbAok/cg28jxg0LAov2GA/aNzLHpGsAGhDhm3EhGs4ALMDGup1JLYlUhzCwLHJyYnIwkZiYgIFjyvwpA+kHQCH1uvLKKw0YAA4woxyQYX74ASzSFT+w8C/Ewj3tMZkAlD9Soz2TPplFe5QBWKwP0ZZJC/Fn7qGv9Jn+Uw6w6CdQCAUWi9KkqLRrvruRL7Xje+UELHMvZcboL2UGhH4QA2ZgaerRLwR4ATqQpr753oxBCLAAHd8XWPLJWNiARZ+GNLCcnJgITPywPVqBaCD8NTvcm6sAHm0QfQRloqQcRD8y+qPvtJetAAD+UMiY8BlnrK33G9hSj/r+iIkU2si3lmgbZ/wdnfuwnJzCUwYn1vCICgdJRKImIiWaZUGdaBDAfrA3jjo5EWGQqhg5CUCQOmowxTofqSqpHWuORGDvPzlgOTk5OWA5OTk5OWA5OTk5OWA5OTk5YDk5OTk5YDk5OTn9HyyiWpfulI5BAAAAAElFTkSuQmCC" alt="Logo"/>
 
<p>
Oops! Probably Codeforces can't be reached right now or your Internet connection is broken. You can try:
</p>
 
<ul>
<li>reload the page <a href=""><img src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAA8AAAAPCAMAAAAMCGV4AAAAclBMVEX+//////8CTc0CTc1Vkd4aY9IRW9Aka9SAr+YwdNZjnOFIh9sQW9AJU89ypuMIU89Wkt5nnuI7ftkaYtI8fdmEsuc+gNkka9NypeNkm+AQWtBIh9xxpuRknOBWkd5Jh9xJh9s7fdkZYtIJU84IVM8vdNbVRuLtAAAAA3RSTlMAAPvQGe9KAAAAbElEQVR4XlXNxRICMRQF0Q4vOiq4+///IpBUUkzvzuZeFLE1AEol47uZ/W6vj5ti31VDPb232Yz6S7dssqlXYA59MQFsKz+fzppYK9HV5QqO8qdvd3jY4rT8lGyCM7YXkWxM85J/AyILZobkDy/zBFFnVIipAAAAAElFTkSuQmCC" alt="Reload"/></a></li>
<li>return to <a href="/">the main page</a></li>
<li>visit <a href="http://m1.codeforces.com">m1.codeforces.com</a>, <a href="http://m2.codeforces.com">m2.codeforces.com</a> or <a href="http://m3.codeforces.com">m3.codeforces.com</a> (if you are taking part in the official round right now)
</ul>
 
<p>
Упс! Возможно, Codeforces временно недоступен прямо сейчас или есть проблемы с вашим Интернет-соединением. Вы можете:
</p>
 
<ul>
<li>перезагрузить страницу <a href=""><img src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAA8AAAAPCAMAAAAMCGV4AAAAclBMVEX+//////8CTc0CTc1Vkd4aY9IRW9Aka9SAr+YwdNZjnOFIh9sQW9AJU89ypuMIU89Wkt5nnuI7ftkaYtI8fdmEsuc+gNkka9NypeNkm+AQWtBIh9xxpuRknOBWkd5Jh9xJh9s7fdkZYtIJU84IVM8vdNbVRuLtAAAAA3RSTlMAAPvQGe9KAAAAbElEQVR4XlXNxRICMRQF0Q4vOiq4+///IpBUUkzvzuZeFLE1AEol47uZ/W6vj5ti31VDPb232Yz6S7dssqlXYA59MQFsKz+fzppYK9HV5QqO8qdvd3jY4rT8lGyCM7YXkWxM85J/AyILZobkDy/zBFFnVIipAAAAAElFTkSuQmCC" alt="Перезагрузить"/></a>;</li>
<li>вернуться на <a href="/">главную страницу</a>;</li>
<li>перейти на <a href="http://m1.codeforces.com">m1.codeforces.com</a>, <a href="http://m2.codeforces.com">m2.codeforces.com</a>
или <a href="http://m3.codeforces.com">m3.codeforces.com</a> (если в настоящий момент вы участвуете в официальном раунде).
</ul>
 
</body>
</html>

```

**Comment by GaurangTandon** [comment] 2020-04-10 12:36
Ah, right, of course this is the way to go. I'll deploy a fix by tomorrow, thanks!

**Comment by GaurangTandon** [comment] 2020-04-23 12:46
Fixed in https://github.com/GaurangTandon/codeforces-darktheme/commit/a11094061b97d34acde5b78d26f54473a953b8e2, sorry for the delay, as I was testing it locally for a while and forgot to bump version.

**Closed by GaurangTandon** 2020-04-23 12:46 UTC
