### ISSUE TITLE
dark theme is not working since evening on codeforces, kindly resolve (chrome browser)

### ISSUE THREAD

**Issue by govind-ik** [GaurangTandon/codeforces-darktheme#52] opened 2024-10-20 14:04 UTC

**Comment by Sujansinhthakor** [comment] 2024-10-21 07:04
same here

**Comment by longwatermelon** [comment] 2024-10-22 21:14
Using tampermonkey legacy fixed it for me

**Comment by ljfp** [comment] 2024-10-25 16:29
It seems that this script only works with Tampermonkey Legacy (MV2).

**Comment by GaurangTandon** [comment] 2024-10-25 18:08
Hi all! Thanks for reporting this issue. It looks like the issue is due to Tampermonkey's latest update:

https://github.com/tampermonkey/tampermonkey/issues/2201

As a workaround, please install Tampermonkey beta version in which this issue is fixed. You can install it from here:

https://chromewebstore.google.com/detail/tampermonkey-beta/gcalenpjmijncebpfijmoaglllgpjagf

I sincerely regret the inconvenience. I am closing this issue report as the issue is with the external tool and a workaround is also available.

**Closed as completed by GaurangTandon** 2024-10-25 18:08 UTC
